### ISSUE TITLE
Add support for `MarshalJSON`

### ISSUE THREAD

**Issue by jamietanna** [omissis/go-jsonschema#241]
I couldn't seem to see anything around why there may not be a `MarshalJSON` method as well as an `UnmarshalJSON`, is that intended?

**Comment by jamietanna** [comment]
~Actually maybe this isn't needed, and I may have thought it was needed due to #242~

This may _only_ be needed alongside #242 where a custom `MarshalJSON` is needed?

**Comment by jamietanna** [comment]
This could alternatively be a new `Validator` that handles the generation of 

Example (Apache-2.0 licensed) code that's output from `oapi-codegen` for the same purpose:

```go
func (a Pong) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["ping"], err = json.Marshal(a.Ping)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ping': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
```

For the following (OpenAPI):

```yaml
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
      additionalProperties:
        type: string
```
